export const TYPE_NOTIFICATION_VALUES = [
  'RESERVATION',
  'RESERVATION_CONFIRMEE',
  'RESERVATION_ANNULEE',
  'RESERVATION_TERMINEE',
  'PAIEMENT',
  'PAIEMENT_RECU',
  'PAIEMENT_ECHEC',
  'RETRAIT',
  'MESSAGE',
  'NOUVEAU_MESSAGE',
  'ABONNEMENT',
  'SOUSCRIPTION_ACCEPTEE',
  'SOUSCRIPTION_EXPIRE',
  'ABONNEMENT_ACTIF',
  'BOOST',
  'BOOST_TERMINEE',
  'BOOST_DEBUT',
  'TRADE_IN',
  'TRADE_IN_ACCEPTE',
  'TRADE_IN_REJETE',
  'CERTIFICATION',
  'CERTIFICATION_APPROUVEE',
  'CERTIFICATION_REJETEE',
  'ASSURANCE',
  'ASSURANCE_SOUSCRITE',
  'ASSURANCE_EXPIRE',
  'SYSTEM',
  'MARKETING',
] as const;
export type TypeNotification = (typeof TYPE_NOTIFICATION_VALUES)[number];

export const TYPE_ENTITE_SIGNALABLE_VALUES = [
  'ANNONCE',
  'UTILISATEUR',
  'MESSAGE',
  'AVIS',
  'VEHICULE',
  'COMMENTAIRE',
] as const;
export type TypeEntiteSignalable = (typeof TYPE_ENTITE_SIGNALABLE_VALUES)[number];

export const MOTIF_SIGNALEMENT_VALUES = [
  'CONTENU_INAPPROPRIE',
  'FAKE_ANNONCE',
  'PRIX_TROMPEUR',
  'HARCELEMENT',
  'FRAUDE',
  'ARNAQUE',
  'PHOTO_TROMPEUSE',
  'DESCRIPTION_INCORRECTE',
  'VEHICULE_ENDOMMAGE',
  'SPAM',
  'MULTI_POST',
  'AUTRE',
] as const;
export type MotifSignalement = (typeof MOTIF_SIGNALEMENT_VALUES)[number];

export const STATUT_TRAITEMENT_SIGNALEMENT_VALUES = ['EN_ATTENTE', 'EN_COURS', 'TRAITE', 'REJETE', 'RESOLU'] as const;
export type StatutTraitementSignalement = (typeof STATUT_TRAITEMENT_SIGNALEMENT_VALUES)[number];
