export const ALLOWED_USER_TYPES = [
  'UTILISATEUR',
  'ACHETEUR',
  'VENDEUR',
  'CONCESSIONNAIRE',
  'LOCATAIRE',
  'PROPRIETAIRE_LOUEUR',
] as const;

export const RESTRICTED_USER_TYPES = [
  'ADMIN',
  'MODERATEUR',
  'SUPER_ADMIN',
  'COMPAGNIE_ASSURANCE',
  'INSPECTEUR',
  'GARAGE',
  'PARTENAIRE_FINANCIER',
] as const;
