export const ALLOWED_USER_TYPES = [
  'UTILISATEUR',
  'UTILISATEUR',
  'UTILISATEUR',
  'PROFESSIONNEL',
  'LOCATAIRE',
  'PROFESSIONNEL',
] as const;

export const RESTRICTED_USER_TYPES = [
  'ADMIN',
  'ADMIN',
  'ADMIN',
  'PROFESSIONNEL',
  'EXPERT',
  'PROFESSIONNEL',
  'PARTENAIRE_FINANCIER',
] as const;
