export const ROLE_ADMIN = 'ADMIN';
export const ROLE_MODERATEUR = 'MODERATEUR';
export const ROLE_SUPER_ADMIN = 'SUPER_ADMIN';
export const ROLE_INSPECTEUR = 'INSPECTEUR';
export const ROLE_COMPAGNIE_ASSURANCE = 'COMPAGNIE_ASSURANCE';
export const ROLE_PROPRIETAIRE_LOUEUR = 'PROPRIETAIRE_LOUEUR';
export const ROLE_VENDEUR = 'VENDEUR';
export const ROLE_CONCESSIONNAIRE = 'CONCESSIONNAIRE';

export const ROLES_STRICT_ADMIN = [ROLE_ADMIN] as const;
export const ROLES_ADMIN_MODERATION = [ROLE_ADMIN, ROLE_MODERATEUR, ROLE_SUPER_ADMIN] as const;
export const ROLES_ADMIN_SUPER_ADMIN = [ROLE_ADMIN, ROLE_SUPER_ADMIN] as const;
export const ROLES_INSPECTION = [...ROLES_ADMIN_MODERATION, ROLE_INSPECTEUR] as const;
export const ROLES_INSPECTEUR_ONLY = [ROLE_INSPECTEUR] as const;
export const ROLES_VEHICULE_CREATOR = [ROLE_VENDEUR, ROLE_CONCESSIONNAIRE] as const;
export const ROLES_ASSURANCE_MANAGER = [ROLE_COMPAGNIE_ASSURANCE, ROLE_ADMIN] as const;
