export const ROLE_ADMIN = 'ADMIN';
export const ROLE_EXPERT = 'EXPERT';
export const ROLE_PROFESSIONNEL = 'PROFESSIONNEL';
export const ROLE_UTILISATEUR = 'UTILISATEUR';

export const ROLES_STRICT_ADMIN = [ROLE_ADMIN] as const;
export const ROLES_ADMIN_MODERATION = [ROLE_ADMIN] as const;
export const ROLES_ADMIN_SUPER_ADMIN = [ROLE_ADMIN] as const;
export const ROLES_INSPECTION = [ROLE_ADMIN, ROLE_EXPERT] as const;
export const ROLES_INSPECTEUR_ONLY = [ROLE_EXPERT] as const;
export const ROLES_VEHICULE_CREATOR = [ROLE_UTILISATEUR, ROLE_PROFESSIONNEL, ROLE_ADMIN] as const;
export const ROLES_ASSURANCE_MANAGER = [ROLE_PROFESSIONNEL, ROLE_ADMIN] as const;
